// Run after npm run build: electron tests/manual/video-player.cjs
// Uses synthetic videos and an isolated temporary library; never opens user data.
const { app, BrowserWindow } = require('electron')
const { mkdtempSync, mkdirSync, writeFileSync, rmSync } = require('node:fs')
const { tmpdir } = require('node:os')
const { resolve, join } = require('node:path')
const { pathToFileURL } = require('node:url')
const { execFileSync } = require('node:child_process')
const { Worker } = require('node:worker_threads')
const assert = require('node:assert/strict')
const data = mkdtempSync(join(tmpdir(), 'gallery-video-'))
const output = resolve('.preview-appdata/video-player-qa')
mkdirSync(output, { recursive: true })
app.setPath('userData', data)
app.on('will-quit', () => { try { rmSync(data, { recursive: true, force: true }) } catch {} })
const sleep = ms => new Promise(r => setTimeout(r, ms))
async function until(read, message) {
  const deadline = Date.now() + 10000
  while (Date.now() < deadline) { if (await read()) return; await sleep(50) }
  throw new Error(message)
}
const timeout = setTimeout(() => { console.error('Video smoke timed out'); app.exit(1) }, 90000)
;(async () => {
  await import(pathToFileURL(resolve('out/main/index.js')).href)
  const root = join(data, 'media-library'); mkdirSync(root, { recursive: true })
  const sources = []
  for (const [name, size] of [['Landscape', '960x540'], ['Portrait with a long title for checking control layout and truncation', '360x640']]) {
    const path = join(data, name + '.mp4')
    execFileSync(require('ffmpeg-static'), ['-hide_banner', '-loglevel', 'error', '-y', '-f', 'lavfi', '-i', 'testsrc2=size=' + size + ':rate=24', '-t', '15', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', path])
    sources.push({ path, kind: 'file' })
  }
  const worker = new Worker(resolve('out/main/import-worker.js'), { workerData: { databasePath: join(root, 'local-gallery.sqlite'), storagePath: root, deleteSourcesAfterImport: false } })
  let next = 0; const pending = new Map()
  worker.on('message', m => { const p = pending.get(m.id); if (m.type === 'response' && p) { pending.delete(m.id); m.result?.error ? p.reject(new Error(m.result.error)) : p.resolve(m.result) } })
  const request = (command, payload) => new Promise((resolve, reject) => { const id = String(++next); pending.set(id, { resolve, reject }); worker.postMessage({ id, command, payload }) })
  const coser = await request('create-coser', { name: '播放器验收', aliases: [] })
  const job = await request('plan', sources)
  await until(async () => (await request('get-jobs')).some(item => item.id === job.id && item.status === 'completed'), 'Seed import failed')
  await worker.terminate()
  await app.whenReady()
  await until(() => BrowserWindow.getAllWindows()[0]?.webContents.getURL().startsWith('file:'), 'Window did not load')
  const window = BrowserWindow.getAllWindows()[0]; window.show(); window.webContents.setBackgroundThrottling(false)
  const js = async source => { try { return await window.webContents.executeJavaScript(source.includes('await ') ? '(async () => {' + source + '})()' : source, true) } catch (error) { console.error('Failed renderer script:', source); throw error } }
  const click = label => js('document.querySelector(' + JSON.stringify('[aria-label="' + label + '"]') + ').click()')
  const key = value => js('document.querySelector(".cinema-player").dispatchEvent(new KeyboardEvent("keydown", {key:' + JSON.stringify(value) + ',bubbles:true,cancelable:true}))')
  const shot = async name => { await sleep(200); const image = await window.webContents.capturePage(); writeFileSync(join(output, name + '.png'), image.toPNG()) }
  await until(() => js("Boolean(document.querySelector('#app').__vue_app__?.config.globalProperties.$pinia?._s.get('playback'))"), 'Renderer not mounted')
  await js("location.hash = '/library'")
  await until(() => js("document.querySelectorAll('[aria-label^=\"打开 \"]').length === 2"), 'Library cards missing')
  await click('打开 Landscape.mp4')
  await until(() => js("document.querySelector('video')?.currentTime > 0"), 'Video did not play')
  await click('暂停'); await shot('landscape')
  assert(await js("document.querySelector('video').paused"))
  await js("window.oldVideo = document.querySelector('video'); document.querySelector('[aria-label=播放进度]').value = 5; document.querySelector('[aria-label=播放进度]').dispatchEvent(new Event('input',{bubbles:true}))")
  assert(Math.abs(await js('oldVideo.currentTime') - 5) < 0.5)
  await key('ArrowRight'); assert(Math.abs(await js('oldVideo.currentTime') - 10) < 0.5)
  await js("document.querySelector('[aria-label=播放速度]').value = '1.5'; document.querySelector('[aria-label=播放速度]').dispatchEvent(new Event('change',{bubbles:true}))")
  assert.equal(await js('oldVideo.playbackRate'), 1.5)
  await click('静音'); assert(await js('oldVideo.muted'))
  await click('全屏'); await until(() => js('Boolean(document.fullscreenElement)'), 'Fullscreen failed')
  await key('Escape'); await until(() => js('!document.fullscreenElement'), 'Escape did not exit fullscreen')
  assert(await js("Boolean(document.querySelector('video'))"))
  await js('oldVideo.currentTime = 14.8; oldVideo.play()')
  await until(() => js('oldVideo.ended'), 'Single preview did not end')
  assert(await js("document.querySelector('video') === oldVideo && oldVideo.paused"), 'Single preview advanced unexpectedly')
  await click('下一项')
  await until(() => js("document.querySelector('video')?.videoHeight > document.querySelector('video')?.videoWidth"), 'Portrait did not load')
  assert(await js('oldVideo.paused && !oldVideo.getAttribute("src")'))
  await click('暂停'); window.setSize(1080, 720); await sleep(150); await shot('portrait-small-window')
  await click('播放'); window.webContents.sendInputEvent({ type: 'mouseMove', x: 540, y: 360 }); await sleep(3400)
  assert(await js("document.querySelector('.cinema-player').classList.contains('cursor-none')"), 'Controls did not hide')
  await js("document.querySelector('.cinema-player').dispatchEvent(new MouseEvent('mousemove',{bubbles:true}))")
  assert(await js("!document.querySelector('.cinema-player').classList.contains('cursor-none')"))
  await key('Escape'); await until(() => js("!document.querySelector('video')"), 'Viewer did not close')
  await click('归入 Coser')
  await until(() => js("Boolean(document.querySelector('[role=dialog] input[aria-label=\"搜索姓名或别名\"]'))"), 'Coser picker did not open')
  await js("[...document.querySelectorAll('[role=dialog] button')].find(b=>b.textContent.trim()==='播放器验收').click()")
  await js("[...document.querySelectorAll('[role=dialog] button')].find(b=>b.textContent.includes('归入 播放器验收')).click()")
  await until(() => js("document.querySelectorAll('[aria-label^=\"打开 \"]').length === 1"), 'Assigned video remained in library')
  await js('location.hash = ' + JSON.stringify('/cosers?coser=' + coser.id))
  await until(() => js("Boolean(document.querySelector('[aria-label^=\"打开 \"]'))"), 'Standalone Coser card missing')
  await shot('coser-video')
  await js("window.qaPlayback=document.querySelector('#app').__vue_app__.config.globalProperties.$pinia._s.get('playback'); window.qaVideos=(await window.api.library.getSnapshot()).looseMedia; qaVideos.push(...(await window.api.library.getCoser('" + coser.id + "')).videos); qaPlayback.addMediaBatch(qaVideos,'Smoke'); qaPlayback.loop=false; qaPlayback.play()")
  await until(() => js("document.querySelector('video')?.currentTime > 0"), 'Queue did not play')
  await js("document.querySelector('video').currentTime = 14.8")
  await until(() => js('qaPlayback.currentIndex === 1'), 'Queue did not advance')
  await until(() => js("document.querySelector('video')?.currentTime > 0"), 'Next queued video did not play')
  await js("document.querySelector('video').currentTime = 14.8")
  await until(() => js('!qaPlayback.isPlaying'), 'Queue did not stop at end')
  await js('qaPlayback.clear(); qaPlayback.addMediaBatch([qaVideos[0]], "Loop"); qaPlayback.loop=true; qaPlayback.play()')
  await until(() => js("document.querySelector('video')?.currentTime > 0"), 'Loop video did not start')
  await js("document.querySelector('video').currentTime = 14.8")
  await until(() => js("document.querySelector('video').currentTime < 2 && !document.querySelector('video').paused"), 'Single video did not loop')
  await js('qaPlayback.playerOpen=false')
  await until(() => js("!document.querySelector('video')"), 'Queue did not close')
  await js("qaPlayback.clear(); qaPlayback.imageIntervalSeconds=1; qaPlayback.loop=false; window.qaImage={id:'image1', originalName:'Image regression', mediaKind:'image', mediaUrl:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"600\" height=\"400\"><rect width=\"100%\" height=\"100%\" fill=\"purple\"/></svg>'), previewUrl:null}; qaPlayback.addMediaBatch([qaImage,qaVideos[0],{...qaImage,id:'image2'}],'Mixed'); qaPlayback.play()")
  await until(() => js('qaPlayback.currentIndex === 1'), 'Image timer did not advance to video')
  await until(() => js("document.querySelector('video')?.currentTime > 0"), 'Mixed queue video did not play')
  await js("qaPlayback.imageIntervalSeconds=120; document.querySelector('video').currentTime=14.8")
  await until(() => js("qaPlayback.currentIndex === 2 && document.querySelector('[role=dialog] img')?.complete"), 'Video did not advance to image')
  await until(() => js("document.activeElement?.getAttribute('aria-label') === '隐藏播放控件'"), 'Image keyboard focus not restored').catch(async error => { console.error(await js('document.activeElement.outerHTML.slice(0, 300)')); throw error })
  window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Escape' })
  window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Escape' })
  await until(() => js('!qaPlayback.playerOpen'), 'Image Escape did not close mixed queue')
  await js("qaPlayback.clear(); qaPlayback.addMediaBatch([{...qaVideos[0],id:'broken',mediaUrl:'gallery-media://missing'}],'Error'); qaPlayback.play()")
  await until(() => js("Boolean(document.querySelector('.cinema-player [role=alert]'))"), 'Decode error not shown')
  assert(await js("document.querySelector('[aria-label=播放进度]').disabled"), 'Unknown duration allowed seeking')
  await key('Escape')
  console.log('PASS: decode, seek, shortcuts, rate, mute, fullscreen, cleanup, portrait/small-window, auto-hide, Coser UI, queue advance/stop/loop, single preview end, mixed image/video queue, error state')
  clearTimeout(timeout); app.quit()
})().catch(error => { console.error(error); clearTimeout(timeout); app.exit(1) })
