<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { FolderOpen, Plus, UserRound } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import Badge from '@/components/ui/Badge.vue'
type Album = { id: string; title: string; media: number; videos: number; updated: string; covers: string[] }
type Profile = { id: string; name: string; initials: string; media: number; colors: string; albums: Album[] }
const route = useRoute(); const router = useRouter()
const profiles: Profile[] = [{ id: 'linyou', name: '林柚', initials: '柚', media: 128, colors: 'from-fuchsia-500 via-rose-400 to-orange-200', albums: [{ id: 'summer', title: '夏日写真集', media: 24, videos: 2, updated: '今天更新', covers: ['from-fuchsia-500 to-rose-200', 'from-violet-700 to-fuchsia-400', 'from-orange-300 to-pink-300'] }, { id: 'night', title: '城市夜景', media: 32, videos: 0, updated: '8 月 30 日', covers: ['from-slate-950 to-blue-700', 'from-indigo-700 to-sky-400', 'from-slate-800 to-violet-500'] }] }, { id: 'momo', name: 'Momo', initials: 'M', media: 96, colors: 'from-violet-600 via-purple-400 to-pink-200', albums: [{ id: 'summer', title: '夏日写真集', media: 24, videos: 2, updated: '今天更新', covers: ['from-violet-600 to-pink-200', 'from-fuchsia-500 to-rose-300', 'from-indigo-600 to-violet-300'] }] }, { id: 'xiaoman', name: '小满', initials: '满', media: 174, colors: 'from-sky-600 via-cyan-400 to-teal-200', albums: [{ id: 'con', title: '漫展现场', media: 36, videos: 8, updated: '昨天更新', covers: ['from-sky-600 to-cyan-300', 'from-indigo-700 to-violet-400', 'from-teal-500 to-emerald-200'] }] }, { id: 'aying', name: '阿樱', initials: '樱', media: 82, colors: 'from-indigo-700 via-blue-500 to-sky-200', albums: [{ id: 'night', title: '城市夜景', media: 32, videos: 0, updated: '8 月 30 日', covers: ['from-slate-950 to-blue-700', 'from-indigo-700 to-sky-400', 'from-slate-800 to-violet-500'] }] }]
const selected = computed(() => profiles.find(profile => profile.id === route.query.coser) ?? profiles[0])
function select(profile: Profile): void { void router.replace({ name: 'cosers', query: { coser: profile.id } }) }
</script>
<template><div class="p-6 lg:p-8"><div class="mb-5 flex items-end justify-between"><div><div class="flex items-center gap-2"><h2 class="text-2xl font-semibold tracking-tight text-foreground">Coser</h2><Badge>{{ profiles.length }} 人</Badge></div><p class="mt-1.5 text-sm text-muted">选择人物，查看关联图集。</p></div><Button><Plus :size="17" />新建 Coser</Button></div><section class="mb-7 rounded-card border border-line bg-surface p-3"><div class="flex gap-3 overflow-x-auto pb-1"><button v-for="profile in profiles" :key="profile.id" :class="['relative flex min-w-24 flex-col items-center rounded-lg px-3 py-2.5 transition', selected.id === profile.id ? 'bg-violet-500/12 text-violet-700 dark:text-violet-200' : 'text-muted hover:bg-surface-hover hover:text-foreground']" @click="select(profile)"><span :class="['grid size-16 place-items-center rounded-full border-2 bg-gradient-to-br text-xl text-white shadow-md', profile.colors, selected.id === profile.id ? 'border-violet-500 ring-2 ring-violet-500/15' : 'border-white/70 opacity-75 dark:border-white/20']">{{ profile.initials }}</span><span class="mt-2 text-sm font-medium">{{ profile.name }}</span><span class="mt-0.5 text-xs opacity-75">{{ profile.media }} 项</span></button></div></section><section><div class="mb-3 flex items-center gap-2"><h3 class="font-semibold text-foreground">{{ selected.name }} 的图集</h3><span class="text-sm text-muted">{{ selected.albums.length }}</span></div><div v-if="selected.albums.length" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"><button v-for="album in selected.albums" :key="album.id" class="group overflow-hidden rounded-lg border border-line bg-surface text-left transition hover:border-violet-400 hover:shadow-lg" @click="router.push({ name: 'album-detail', params: { id: album.id } })"><div class="relative aspect-[16/9] bg-zinc-900 p-1.5"><div class="grid h-full grid-cols-[1.35fr_1fr] gap-1"><div :class="['rounded bg-gradient-to-br', album.covers[0]]"></div><div class="grid grid-rows-2 gap-1"><div :class="['rounded bg-gradient-to-br', album.covers[1]]"></div><div :class="['rounded bg-gradient-to-br', album.covers[2]]"></div></div></div><span class="absolute bottom-2 left-2 rounded bg-black/40 px-1.5 py-0.5 text-[11px] text-white">{{ album.media }} 项 · {{ album.videos }} 视频</span></div><div class="flex items-center justify-between p-2.5"><div><p class="text-sm font-semibold text-foreground">{{ album.title }}</p><p class="mt-0.5 text-[11px] text-muted">{{ album.updated }}</p></div><FolderOpen class="text-muted" :size="16" /></div></button></div><div v-else class="grid min-h-48 place-items-center rounded-card border border-dashed border-line"><div class="text-center"><UserRound class="mx-auto text-muted" :size="22" /><p class="mt-3 text-sm text-muted">还没有关联图集</p></div></div></section></div></template>
