<script setup lang="ts">
import { AlertTriangle, CheckCircle2, Database, FolderOpen, HardDrive, Image, Trash2, Video } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'

const sources = [
  { name: '写真收藏', path: 'D:\\Gallery\\Portraits', used: '16.2 GB', media: 286, status: 'ready', fill: 68 },
  { name: '漫展记录', path: 'E:\\Cosplay\\Events', used: '11.4 GB', media: 135, status: 'ready', fill: 46 },
  { name: '移动硬盘备份', path: 'F:\\Archive\\2025', used: '5.2 GB', media: 74, status: 'offline', fill: 22 }
]
const albums = [
  { name: '漫展现场', size: '8.4 GB', media: 36, color: 'bg-sky-500' },
  { name: '城市夜景', size: '6.7 GB', media: 32, color: 'bg-indigo-500' },
  { name: '夏日写真集', size: '5.2 GB', media: 24, color: 'bg-violet-500' },
  { name: '日常收藏', size: '2.1 GB', media: 15, color: 'bg-amber-500' }
]
</script>

<template>
  <div class="mx-auto max-w-6xl p-6 lg:p-8">
    <div><h2 class="text-2xl font-semibold tracking-tight text-foreground">存储空间</h2><p class="mt-1.5 text-sm text-muted">查看已索引内容、来源目录与缩略图缓存的本地占用。</p></div>
    <section class="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="rounded-xl border border-line bg-surface p-4"><div class="flex items-center justify-between text-muted"><span class="text-sm">已索引媒体</span><Image :size="17" /></div><p class="mt-3 text-2xl font-semibold text-foreground">421</p><p class="mt-1 text-xs text-muted">375 张图片 · 46 个视频</p></article><article class="rounded-xl border border-line bg-surface p-4"><div class="flex items-center justify-between text-muted"><span class="text-sm">媒体总容量</span><HardDrive :size="17" /></div><p class="mt-3 text-2xl font-semibold text-foreground">32.8 <span class="text-sm font-medium text-muted">GB</span></p><p class="mt-1 text-xs text-muted">仅统计已索引原文件</p></article><article class="rounded-xl border border-line bg-surface p-4"><div class="flex items-center justify-between text-muted"><span class="text-sm">图片占用</span><Image :size="17" /></div><p class="mt-3 text-2xl font-semibold text-foreground">18.6 <span class="text-sm font-medium text-muted">GB</span></p><p class="mt-1 text-xs text-muted">约 56.7%</p></article><article class="rounded-xl border border-line bg-surface p-4"><div class="flex items-center justify-between text-muted"><span class="text-sm">视频占用</span><Video :size="17" /></div><p class="mt-3 text-2xl font-semibold text-foreground">14.2 <span class="text-sm font-medium text-muted">GB</span></p><p class="mt-1 text-xs text-muted">约 43.3%</p></article></section>
    <section class="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(300px,.7fr)]"><article class="rounded-xl border border-line bg-surface p-5"><div><h3 class="font-semibold text-foreground">来源目录</h3><p class="mt-1 text-xs text-muted">原始文件仍保留在这些本地目录中。</p></div><div class="mt-5 space-y-4"><div v-for="source in sources" :key="source.name" class="rounded-lg bg-canvas p-3.5"><div class="flex items-start gap-3"><div class="grid size-9 shrink-0 place-items-center rounded-lg" :class="source.status === 'ready' ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' : 'bg-amber-500/10 text-amber-600 dark:text-amber-400'"><FolderOpen :size="18" /></div><div class="min-w-0 flex-1"><div class="flex items-center justify-between gap-3"><p class="truncate text-sm font-medium text-foreground">{{ source.name }}</p><span v-if="source.status === 'ready'" class="inline-flex items-center gap-1 text-xs text-emerald-600 dark:text-emerald-400"><CheckCircle2 :size="14" />正常</span><span v-else class="inline-flex items-center gap-1 text-xs text-amber-600 dark:text-amber-400"><AlertTriangle :size="14" />已断开</span></div><p class="mt-0.5 truncate font-mono text-[11px] text-muted">{{ source.path }}</p><div class="mt-3 flex items-center justify-between text-xs text-muted"><span>{{ source.media }} 项 · {{ source.used }}</span><span>{{ source.fill }}%</span></div><div class="mt-1.5 h-1.5 overflow-hidden rounded-full bg-line"><div class="h-full rounded-full" :class="source.status === 'ready' ? 'bg-violet-500' : 'bg-amber-500'" :style="{ width: `${source.fill}%` }"></div></div></div></div></div></div></article>
      <div class="space-y-5"><article class="rounded-xl border border-line bg-surface p-5"><h3 class="font-semibold text-foreground">媒体类型占用</h3><div class="mt-5 grid place-items-center"><div class="grid size-36 place-items-center rounded-full" style="background: conic-gradient(#8b5cf6 0 56.7%, #38bdf8 56.7% 100%)"><div class="grid size-24 place-items-center rounded-full bg-surface text-center"><strong class="text-xl text-foreground">32.8</strong><span class="text-[11px] text-muted">GB 总容量</span></div></div></div><div class="mt-5 space-y-3 text-sm"><div class="flex items-center justify-between"><span class="flex items-center gap-2 text-foreground"><span class="size-2.5 rounded-full bg-violet-500"></span>图片</span><span class="text-muted">18.6 GB</span></div><div class="flex items-center justify-between"><span class="flex items-center gap-2 text-foreground"><span class="size-2.5 rounded-full bg-sky-400"></span>视频</span><span class="text-muted">14.2 GB</span></div></div></article><article class="rounded-xl border border-line bg-surface p-5"><div class="flex items-center justify-between"><div><h3 class="font-semibold text-foreground">缩略图缓存</h3><p class="mt-1 text-xs text-muted">图片缩略图与视频封面</p></div><Database class="text-violet-500" :size="19" /></div><p class="mt-5 text-2xl font-semibold text-foreground">682 <span class="text-sm font-medium text-muted">MB</span></p><Button variant="outline" size="sm" class="mt-4 w-full"><Trash2 :size="15" />清理缓存</Button></article></div></section>
    <section class="mt-6 rounded-xl border border-line bg-surface p-5"><h3 class="font-semibold text-foreground">图集容量排行</h3><p class="mt-1 text-xs text-muted">根据关联媒体的原始文件大小估算。</p><div class="mt-5 grid gap-x-8 gap-y-4 md:grid-cols-2"><div v-for="(album, index) in albums" :key="album.name" class="grid grid-cols-[24px_minmax(0,1fr)] gap-3"><span class="text-sm font-medium text-muted">0{{ index + 1 }}</span><div><div class="flex justify-between gap-3 text-sm"><span class="truncate font-medium text-foreground">{{ album.name }}</span><span class="shrink-0 text-muted">{{ album.size }}</span></div><div class="mt-2 h-1.5 overflow-hidden rounded-full bg-line"><div class="h-full rounded-full" :class="album.color" :style="{ width: `${100 - index * 18}%` }"></div></div><p class="mt-1.5 text-[11px] text-muted">{{ album.media }} 项媒体</p></div></div></div></section>
  </div>
</template>
